### Crear un nuevo artículo
POST http://localhost:3000/api/articulos
Content-Type: application/json

{
  "codigoArticulo": "ART05",
  "nombre": "Articulo 5",
  "descripcion": "Descripción del Artículo 5",
  "precio": 500.0,
  "idColor": 5,
  "idCategoria": 1
}

### Actualizar un artículo por su código
PUT http://localhost:3000/api/articulos/ART123
Content-Type: application/json

{
  "nombre": "Articulo 1 Actualizado",
  "descripcion": "Descripción actualizada del Artículo 1",
  "precio": 150.0,
  "idColor": 2,
  "idCategoria": 2
}

### Eliminar un artículo por su código
DELETE http://localhost:3000/api/articulos/ART123

### Obtener todos los artículos
GET http://localhost:3000/api/articulos

### Obtener artículos por categoría
GET http://localhost:3000/api/articulos/categoria/1

### Buscar artículos por término en nombre o descripción
GET http://localhost:3000/api/articulos/search?q=Articulo

### Obtener un artículo por su código
GET http://localhost:3000/api/articulos/ART123


### Crear un nuevo artículo
POST http://localhost:3000/api/articulos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiY3Jpczk5MDA3N0Bob3RtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkNyaXNDcmlzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yRmVpSldUIiwiYXVkIjoiQ2xpZW50ZXNGZWlKV1QiLCJpYXQiOjE3MTc0NzY2NTIsImV4cCI6MTcxNzQ3ODQ1Mn0.R9dTK4QHEfGJ_XZsgi4xAnTHLqi7qPX0b_wkt9X49lA

{
  "codigoArticulo": "ART02",
  "nombre": "Sudadera Evangelion",
  "descripcion": "Sudadera parte de la colaboración entre XKBAM y la franquicia de anime evangelion",
  "precio": 600.0,
  "idColor": 1,
  "idCategoria": 1
}

###

PUT http://localhost:3000/api/articulos/ART02
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiY3Jpczk5MDA3N0Bob3RtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkNyaXNDcmlzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yRmVpSldUIiwiYXVkIjoiQ2xpZW50ZXNGZWlKV1QiLCJpYXQiOjE3MTc0NzY2NTIsImV4cCI6MTcxNzQ3ODQ1Mn0.R9dTK4QHEfGJ_XZsgi4xAnTHLqi7qPX0b_wkt9X49lA

{
  "codigoArticulo": "ART02",
  "nombre": "Sudadera Evangelion",
  "descripcion": "Sudadera parte de la colaboración entre XKBAM y la franquicia de anime evangelion",
  "precio": 600.0,
  "idColor": 1,
  "idCategoria": 1
}


