###
POST  http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correo": "jasielzav@gmail.com",
    "contrasena": "DRACULA123"

}
###


POST  http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correo": "jasielzav@gmail.com",
    "contrasena": "123"

}

