###
POST  http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correo": "jasielzav@gmail.com",
    "contrasena": "DRACULA123"

}
###
POST  http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correo": "cris990077@hotmail.com",
    "contrasena": "CrisCris8"
}
###

POST  http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correo": "jasielzav@gmail.com",
    "contrasena": "123"

}
###

GET  http://localhost:3000/api/autenticacion/tiempo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiamFzaWVsemF2QGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6Ikphc2llbE1hc3RlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudGUiLCJpc3MiOiJTZXJ2aWRvckZlaUpXVCIsImF1ZCI6IkNsaWVudGVzRmVpSldUIiwiaWF0IjoxNzE4MzE0NjQxLCJleHAiOjE3MTgzMTUwMDF9.GwZnn9qyW9jEkaFfPe8kkOoGvph_9OobPeRQhQz7Ieg
