###
POST  http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correo": "jasielzav@gmail.com",
    "contrasena": "DRACULA123"

}
###
POST  http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correo": "cris990077@hotmail.com",
    "contrasena": "CrisCris8"
}
###

POST  http://localhost:3000/api/autenticacion
Content-Type: application/json

{
    "correo": "jasielzav@gmail.com",
    "contrasena": "123"

}
###

GET  http://localhost:3000/api/autenticacion/tiempo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiY3Jpczk5MDA3N0Bob3RtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IkNyaXNDcmlzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW5pc3RyYWRvciIsImlzcyI6IlNlcnZpZG9yRmVpSldUIiwiYXVkIjoiQ2xpZW50ZXNGZWlKV1QiLCJpYXQiOjE3MTgzMDQyODcsImV4cCI6MTcxODMwNDY0N30.8-6zR0uZPMEXZgKm7Ei3EkR8MmiN83jM6kMUbhi4Zhg
