POST http://localhost:3000/api/direcciones
Content-Type: application/json

{
    "estado": "Veracruz",
    "municipio": "Xalapa",
    "codigopostal": "91231",
    "calle": "16 de Septiembre",
    "numeroexterno": 22,
    "idusuario": "JasielZ"
}

