POST http://localhost:3000/api/cuentasbancarias
Content-Type: application/json

{
    "numeroTarjeta": "4111111111111111",
    "titular": "Juan Perez",
    "fechaExpiracion": "2025-12-31",
    "cvv": "123",
    "usuario": "diddy1"
}


###