 POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "usuario": "CrisCris",
  "nombre": "Cristopher",
  "apellidoPaterno": "Vazquez",
  "apellidoMaterno": "Villa",
  "genero": 1,
  "contrasena": "CrisCris89",
  "correo": "cris990077@hotmail.com",
  "idRol": 1
}
###
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "usuario": "jasielqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq",
  "nombre": "Q",
  "apellidoPaterno": "Zavaleta",
  "apellidoMaterno": "García",
  "genero": 1,
  "contrasena": "patito2003",
  "correo": "jasielz@gmail.com",
  "idRol": 1
}
###
 POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "usuario": "raulqqqqqqqqqqqqqqqqqqqqqq",
  "nombre": "",
  "apellidoPaterno": "Zavaleta",
  "apellidoMaterno": "García",
  "genero": 1,
  "contrasena": "iker2007",
  "correo": "ikerz@gmail.com",
  "idRol": 1
}
###

 POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  
  "nombre": "",
  "apellidopaterno": "Zavaleta",
  "apellidomaterno": "García",
  "genero": 1,
  "contrasena": "iker2007",
  "correo": "ikerz@gmail.com",
  "idRol": 1
}

###
 POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "usuario": {      
        "usuario": "CrisCris",
        "nombre": "Cristopher",
        "apellidoPaterno": "Vázquez",
        "apellidoMaterno": "Villa",
        "genero": 1
        
    },
    "cuenta": {
        "correo": "cris990077@hotmail.com",
        "contrasena": "CrisCris8",
        "idRol": 1
    }
}

###
 POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "usuario": {      
        "usuario": "Jasiel45",
        "nombre": "Jasiel Emir",
        "apellidoPaterno": "Zavaleta",
        "apellidoMaterno": "García",
        "genero": 1
        
    },
    "cuenta": {
        "correo": "jasiel45@hotmail.com",
        "contrasena": "Jasiel789",
        "idRol": 1
    }
}

###


 POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "usuario": {      
        "usuario": "JasielMaster",
        "nombre": "Jasiel",
        "apellidoPaterno": "Zavaleta",
        "apellidoMaterno": "García",
        "genero": 1
        
    },
    "cuenta": {
        "correo": "jasielzav@gmail.com",
        "contrasena": "DRACULA123",
        "idRol": 2
    }
}

###
 POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "usuario": {      
        "usuario": "diddyc",
        "nombre": "diddy",
        "apellidoPaterno": "d",
        "apellidoMaterno": "d",
        "genero": 1
        
    },
    "cuenta": {
        "correo": "diddy@hotmail.com",
        "contrasena": "d",
        "idRol": 2
    }
}

###
GET http://localhost:3000/api/usuarios/diddy1


###